<div class="estimator-card">
    @if($submitted)
        <div class="estimator-success"><span class="success-mark">&#10003;</span><p class="eyebrow">Request received</p><h3>Thank you, {{ $name }}.</h3><p>Your reference is <strong>{{ $reference }}</strong>. Our team will review the details and contact you to confirm scope, timing and final pricing.</p><a href="https://wa.me/{{ config('company.whatsapp') }}?text={{ urlencode('Hi CuciNow, my quote reference is '.$reference) }}" target="_blank" rel="noopener" class="button">Continue on WhatsApp</a></div>
    @else
        <form wire:submit="submit" class="estimator-form">
            <div class="form-grid two"><label><span>Service</span><select wire:model.live="serviceId">@foreach($this->services as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select>@error('serviceId')<small>{{ $message }}</small>@enderror</label><label><span>Space type</span><select wire:model.live="propertyType"><option value="apartment">Apartment</option><option value="condominium">Condominium</option><option value="landed">Landed home</option><option value="office">Office</option><option value="hall">Grand hall / venue</option><option value="other">Other</option></select></label></div>
            <div class="form-grid two"><label><span>Approximate size</span><select wire:model.live="sizeBand"><option value="under_1000">Under 1,000 sq ft</option><option value="1000_2000">1,000 - 2,000 sq ft</option><option value="2000_5000">2,000 - 5,000 sq ft</option><option value="over_5000">Over 5,000 sq ft</option></select></label><label><span>Frequency</span><select wire:model.live="frequency"><option value="one_off">One-off</option><option value="weekly">Weekly</option><option value="fortnightly">Every 2 weeks</option><option value="monthly">Monthly</option></select></label></div>
            <div class="estimate-band"><div><span>Preliminary estimate</span><strong>RM {{ number_format($this->estimate, 2) }}</strong></div><p>Planning estimate only. Final quote follows scope confirmation.</p></div>
            <div class="form-grid two"><label><span>Preferred date</span><input type="date" wire:model="preferredDate" min="{{ now()->format('Y-m-d') }}">@error('preferredDate')<small>{{ $message }}</small>@enderror</label><label><span>Preferred time</span><select wire:model="preferredTimeSlot"><option value="morning">Morning</option><option value="afternoon">Afternoon</option><option value="evening">Evening</option><option value="flexible">Flexible</option></select></label></div>
            <div class="form-grid two"><label><span>Your name</span><input type="text" wire:model="name" autocomplete="name" placeholder="Full name">@error('name')<small>{{ $message }}</small>@enderror</label><label><span>Mobile number</span><input type="tel" wire:model="phone" autocomplete="tel" placeholder="01X-XXXXXXX">@error('phone')<small>{{ $message }}</small>@enderror</label></div>
            <label><span>Email <em>optional</em></span><input type="email" wire:model="email" autocomplete="email" placeholder="you@example.com">@error('email')<small>{{ $message }}</small>@enderror</label>
            <label><span>Service address</span><textarea wire:model="address" rows="2" placeholder="Unit, building and street"></textarea>@error('address')<small>{{ $message }}</small>@enderror</label>
            <div class="form-grid three"><label><span>Postcode</span><input type="text" wire:model="postcode" inputmode="numeric"></label><label><span>City</span><input type="text" wire:model="city"></label><label><span>State</span><input type="text" wire:model="state"></label></div>
            <label><span>Anything we should know? <em>optional</em></span><textarea wire:model="notes" rows="3" placeholder="Condition, access, preferred scope or special surfaces"></textarea></label>
            <button type="submit" class="button estimator-submit" wire:loading.attr="disabled"><span wire:loading.remove>Submit quote request</span><span wire:loading>Sending...</span><small>Hantar permintaan</small></button>
            <p class="privacy-note">By submitting, you agree that CuciNow may contact you about this request. No payment is taken here.</p>
        </form>
    @endif
</div>
